services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: steam_profiler
      POSTGRES_USER: hades
      POSTGRES_PASSWORD: pg_academy
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
